import {
  xyAvatar, xyAvatarGroup,
  xyBadge,
  xyBarCode,
  xyButton, xyButtonGroup,
  xyCard,
  xyCode,
  xyCover,
  xyDivider,
  xyEmpty,
  xyGrid, xyGridItem,
  xyIcon,
  xyLink,
  xyNumeral,
  xyPoster,
  xyProgress,
  xyQrCode,
  xyRandomText,
  xyRow, xyCol,
  xySpace,
  xyText,
  xyTime,
} from "@xuyou-element/components";
import type {Plugin} from "vue"

export default [
  xyAvatar, xyAvatarGroup,
  xyBadge,
  xyBarCode,
  xyButton, xyButtonGroup,
  xyCard,
  xyCode,
  xyCover,
  xyDivider,
  xyEmpty,
  xyGrid, xyGridItem,
  xyIcon,
  xyLink,
  xyNumeral,
  xyPoster,
  xyProgress,
  xyQrCode,
  xyRandomText,
  xyRow, xyCol,
  xySpace,
  xyText,
  xyTime,
] as Plugin[]